student/urls.py
from turtle import home
from django.contrib import admin
from django.urls import path
from admissionapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home),
    path('studform', views.studform),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('delete/<int:id>', views.erase),
    path('update/<int:id>', views.update),
    path('display/<int:id>', views.display),
    path('filter/<int:id>', views.filter),
]

admissionapp/models.py
from operator import mod
from statistics import mode
from django.db import models


# Create your models here.
class Student(models.Model):
	adm_mode = models.CharField(max_length=20)
	sid = models.CharField(max_length=20)
	adm_date = models.DateField()
	category = models.CharField(max_length=2)
	branch = models.CharField(max_length=10)
	sname = models.CharField(max_length=50)
	sdob = models.DateField()
	quota = models.CharField(max_length=20)
	tneanum = models.CharField(max_length=30)
	admquota = models.CharField(max_length=20)
	firstgrad = models.CharField(max_length=10)
	tnscst = models.CharField(max_length=20)
	tnbc = models.CharField(max_length=20)
	aicte = models.CharField(max_length=20)
	sgender = models.CharField(max_length=10)
	medium = models.CharField(max_length=30)
	nationality = models.CharField(max_length=30)
	religion = models.CharField(max_length=30)
	community = models.CharField(max_length=30)
	caste = models.CharField(max_length=30)
	bloodgroup = models.CharField(max_length=10)
	saadhar = models.CharField(max_length=30)
	smobilenum = models.CharField(max_length=30)
	smail = models.CharField(max_length=50)
	scolmode = models.CharField(max_length=30)
	phychallenged = models.CharField(max_length=10)
	fathername = models.CharField(max_length=30)
	mothername = models.CharField(max_length=30)
	guardianname = models.CharField(max_length=30)
	comaddress = models.CharField(max_length=100)
	permaddress = models.CharField(max_length=100)
	state = models.CharField(max_length=30)

	class Meta:
		db_table="detail"

admissionapp/forms.py
from dataclasses import field
from random import choices
from django import forms
from admissionapp.models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

        ADM_MODES = (
            ("regular", "Regular"),
            ("lateral", 'Lateral'),
            ('readmission', 'Readmission'),
            ('transfer', 'Transfer')
        )

        CATEGORY = (
            ('UG', 'UG'),
            ('PG', 'PG'),
        )

        BRANCHES = (
            ('AIDS', 'AIDS'),	
            ('MBA', 'MBA'),
            ('CIVIL', 'CIVIL'),	
            ('CAD/CAM', 'CAD/CAM'),
            ('CSBS', 'CSBS'),	
            ('CSE', 'CSE'),
            ('CS', 'CS'),
            ('ECE', 'ECE'),	
            ('AE', 'AE'),
            ('EEE', 'EEE'),	
            ('SE', 'SE'),
            ('IT', 'IT'),
            ('ED', 'ED'),
            ('MCT', 'MCT'),
            ('PED', 'PED'),
            ('MECH', 'MECH'),	
            ('M.Tech.CSE', 'M.Tech.CSE')
        )

        QUOTA = (
            ('GQ', 'GQ'),
            ('MQ', 'MQ'),
            ('GQ-LAPSED', 'GQ-LAPSED'),
            ('MQ-LAPSED', 'MQ-LAPSED'),
            ('NRI', 'NRI'),
            ('GOI', 'GOI'),
            ('FOR', 'FOR')
        )

        ADM_QUOTA = (
            ('OC', 'OC'),
            ('BC', 'BC'),
            ('MBC', 'MBC'),
            ('DNC', 'DNC'),
            ('SC', 'SC'),
            ('SCA', 'SCA'),
            ('ST', 'ST'),
            ('Sports', 'Sports'),
            ('Exserviceman', 'Exserviceman'),
            ('Vocational', 'Vocational')
        )

        BOOLEAN_DATA = (
            ('YES', 'YES'),
            ('NO', 'NO')
        )

        TNBC = (
            ('NSP', 'NSP'),
            ('CATEGORY 1', 'CATEGORY 1'),
            ('CATEGORY 2', 'CATEGORY 2'),
            ('CATEGORY 3', 'CATEGORY 3'),
        )

        GENDER = (
            ('MALE', 'MALE'),
            ('FEMALE', 'FEMALE'),
            ('OTHERS', 'OTHERS')
        )

        MEDIUM = (
            ('ENGLISH', 'ENGLISH'),
            ('TAMIL', 'TAMIL'),
            ('OTHERS', 'OTHERS')
        )

        RELIGION = (
            ('Hindu', 'Hindu'),
            ('Christian', 'Christian'),
            ('Muslim', 'Muslim'),
            ('Sikhism', 'Sikhism'),
            ('Buddhism', 'Buddhism'),
            ('Jainism', 'Jainism'),
            ('Judaism', 'Judaism'),
            ('Others', 'Others')
        )

        COMMUNITY = (
            ('OC', 'OC'),
            ('BC', 'BC'),
            ('MBC', 'MBC'),
            ('DNC', 'DNC'),
            ('SC', 'SC'),
            ('SCA', 'SCA'),
            ('ST', 'ST'),
            ('SCC', 'SCC'),
        )

        SCOLMODE = (
            ('HOSTELLER', 'HOSTELLER'),
            ('DAYSCHOLAR', 'DAYSCHOLAR')
        )

        widgets = {
            'adm_mode': forms.Select(choices = ADM_MODES),
            'adm_date': forms.DateTimeInput(attrs={'class': 'datetime-input'}),
            'category': forms.Select(choices = CATEGORY),
            'branch': forms.Select(choices = BRANCHES),
            'sdob': forms.DateTimeInput(attrs={'class': 'datetime-input'}),
            'quota': forms.Select(choices = QUOTA),
            'admquota': forms.Select(choices = ADM_QUOTA),
            'firstgrad': forms.Select(choices = BOOLEAN_DATA),
            'tnscst': forms.Select(choices = BOOLEAN_DATA),
            'tnbc': forms.Select(choices = TNBC),
            'aicte': forms.Select(choices = BOOLEAN_DATA),
            'sgender': forms.Select(choices = GENDER),
            'medium': forms.Select(choices = MEDIUM),
            'religion': forms.Select(choices = RELIGION),
            'community': forms.Select(choices = COMMUNITY),
            'scolmode': forms.Select(choices = SCOLMODE),
            'phychallenged': forms.Select(choices = BOOLEAN_DATA),
        }

admissionapp/views.py
from django.shortcuts import render, redirect
from admissionapp.forms import StudentForm
from admissionapp.models import Student

# Create your views here.


def home(request):
    return render(request, "admissionapp/home.html")


def studform(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            print("HELLO")
            form.save()
            print("AFTER SAVE")
            return redirect('/home')

    else:
        form = StudentForm()
    return render(request, 'admissionapp/create.html', {'form': form})


def show(request):
    students = Student.objects.all()
    return render(request, "admissionapp/show.html", {"students": students})


def edit(request, id):
    student = Student.objects.get(id=id)
    return render(request, 'admissionapp/edit.html', {'student': student})


def update(request, id):
    student = Student.objects.get(id=id)
    form = StudentForm(request.POST, instance=student)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'employee/edit.html', {'employee': student})


def erase(request, id):
    student = Student.objects.get(id=id)
    student.delete()
    return redirect("/home")


def display(request, id):
    student = Student.objects.get(id=id)
    return render(request, 'admissionapp/display.html', {'student': student})


def filter(request, id):
    student = Student.objects.get(id=id)
    return render(request, 'admissionapp/filter.html', {'student': student})

admissionapp/templates/admissionapp/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admission - Create</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
</head>
<form class="post-form" method="POST" action="/studform">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Form Create</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Admission Mode: </label>  
    <div class="col-sm-4">  
        {{ form.adm_mode }} 
    </div>
  </div> 

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Admission Number: </label>  
    <div class="col-sm-4">  
        {{ form.sid }}  
    </div>  
  </div> 

    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Admission Date: </label>  
    <div class="col-sm-4">  
        <div class="input-group date" data-target-input="nearest">
            {{ form.adm_date }}
            <script>
            $(function () {
                $('.datetime-input').datetimepicker({
                    format:'YYYY-MM-DD'
                });
            });
            </script>
        </div>
    </div>  
  </div> 

    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Category: </label>  
    <div class="col-sm-4">  
    {{ form.category }} 
    </div>  
  </div>


  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Branch: </label>  
    <div class="col-sm-4">  
        {{ form.branch }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Student Name: </label>  
    <div class="col-sm-4">  
        {{ form.sname }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Date of Birth: </label>  
    <div class="col-sm-4">  
        {{ form.sdob }}
    </div>  
  </div>


  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Quota: </label>  
    <div class="col-sm-4">  
        {{ form.quota }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">TNEA No.: </label>  
    <div class="col-sm-4">  
        {{ form.tneanum }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Admitted Quota: </label>  
    <div class="col-sm-4">  
        {{ form.admquota }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">First Graduate: </label>  
    <div class="col-sm-4">  
        {{ form.firstgrad }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">TN-SC: </label>  
    <div class="col-sm-4">  
        {{ form.tnscst }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">TN-BC: </label>  
    <div class="col-sm-4">  
        {{ form.tnbc }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">AICTE: </label>  
    <div class="col-sm-4">  
        {{ form.aicte }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Gender: </label>  
    <div class="col-sm-4">  
        {{ form.sgender }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Medium: </label>  
    <div class="col-sm-4">  
        {{ form.medium }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nationality: </label>  
    <div class="col-sm-4">  
        {{ form.nationality }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Religion: </label>  
    <div class="col-sm-4">  
        {{ form.religion }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Community: </label>  
    <div class="col-sm-4">  
        {{ form.community }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Caste: </label>  
    <div class="col-sm-4">  
        {{ form.caste }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Blood Group: </label>  
    <div class="col-sm-4">  
        {{ form.bloodgroup }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Aadhar: </label>  
    <div class="col-sm-4">  
        {{ form.saadhar }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mobile: </label>  
    <div class="col-sm-4">  
        {{ form.smobilenum }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mail: </label>  
    <div class="col-sm-4">  
        {{ form.smail }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Colege mode: </label>  
    <div class="col-sm-4">  
        {{ form.scolmode }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Phy Challenged: </label>  
    <div class="col-sm-4">  
        {{ form.phychallenged }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Father Name: </label>  
    <div class="col-sm-4">  
        {{ form.fathername }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Mother Name: </label>  
    <div class="col-sm-4">  
        {{ form.mothername }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Guardian: </label>  
    <div class="col-sm-4">  
        {{ form.guardianname }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Com Address: </label>  
    <div class="col-sm-4">  
        {{ form.comaddress }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Perm address: </label>  
    <div class="col-sm-4">  
        {{ form.permaddress }}
    </div>  
  </div>

  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">State: </label>  
    <div class="col-sm-4">  
        {{ form.state }}
    </div>  
  </div>

    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Create</button>  
    </div>  
  </div>  
    </div>  
</form> 

</html>

admissionapp/templates/admissionapp/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Admission - Update</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    {% load static %}
  </head>
  <form method="POST" class="post-form" action="/update/{{student.id}}">
    {% csrf_token %}
    <div class="container">
      <br />
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h3>Form Update</h3>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Admission Mode: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="adm_mode"
            id="id_adm_mode"
            required
            maxlength="20"
            value="{{ student.adm_mode }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Admission Number: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="sid"
            id="id_sid"
            required
            maxlength="20"
            value="{{ student.sid }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Admission Date: </label>
        <div class="col-sm-4">
          <div class="input-group date" data-target-input="nearest">
            <input
              type="text"
              name="adm_date"
              id="id_adm_date"
              required
              maxlength="20"
              value="{{ student.adm_date }}"
            />
            <script>
              $(function () {
                $(".datetime-input").datetimepicker({
                  format: "YYYY-MM-DD",
                });
              });
            </script>
          </div>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Category: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="category"
            id="id_category"
            required
            maxlength="20"
            value="{{ student.category }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Branch: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="branch"
            id="id_branch"
            required
            maxlength="20"
            value="{{ student.branch }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Student Name: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="sname"
            id="id_sname"
            required
            maxlength="20"
            value="{{ student.sname }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Date of Birth: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="sdob"
            id="id_sdob"
            required
            maxlength="20"
            value="{{ student.sdob }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Quota: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="quota"
            id="id_quota"
            required
            maxlength="20"
            value="{{ student.quota }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">TNEA No.: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="tneanum"
            id="id_tneanum"
            required
            maxlength="20"
            value="{{ student.tneanum }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Admitted Quota: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="admquota"
            id="id_admquota"
            required
            maxlength="20"
            value="{{ student.admquota }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">First Graduate: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="firstgrad"
            id="id_firstgrad"
            required
            maxlength="20"
            value="{{ student.firstgrad }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">TN-SC: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="tnscst"
            id="id_tnscst"
            required
            maxlength="20"
            value="{{ student.tnscst }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">TN-BC: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="tnbc"
            id="id_tnbc"
            required
            maxlength="20"
            value="{{ student.tnbc }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">AICTE: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="aicte"
            id="id_aicte"
            required
            maxlength="20"
            value="{{ student.aicte }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Gender: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="sgender"
            id="id_sgender"
            required
            maxlength="20"
            value="{{ student.sgender }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Medium: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="medium"
            id="id_medium"
            required
            maxlength="20"
            value="{{ student.medium }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Nationality: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="nationality"
            id="id_nationality"
            required
            maxlength="20"
            value="{{ student.nationality }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Religion: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="religion"
            id="id_religion"
            required
            maxlength="20"
            value="{{ student.religion }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Community: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="community"
            id="id_community"
            required
            maxlength="20"
            value="{{ student.community }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Caste: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="caste"
            id="id_caste"
            required
            maxlength="20"
            value="{{ student.caste }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Blood Group: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="bloodgroup"
            id="id_bloodgroup"
            required
            maxlength="20"
            value="{{ student.bloodgroup }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Aadhar: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="saadhar"
            id="id_saadhar"
            required
            maxlength="20"
            value="{{ student.saadhar }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Mobile: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="smobilenum"
            id="id_smobilenum"
            required
            maxlength="20"
            value="{{ student.smobilenum }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Mail: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="smail"
            id="id_smail"
            required
            maxlength="20"
            value="{{ student.smail }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Colege mode: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="scolmode"
            id="id_scolmode"
            required
            maxlength="20"
            value="{{ student.scolmode }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Phy Challenged: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="phychallenged"
            id="id_phychallenged"
            required
            maxlength="20"
            value="{{ student.phychallenged }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Father Name: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="fathername"
            id="id_fathername"
            required
            maxlength="20"
            value="{{ student.fathername }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Mother Name: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="mothername"
            id="id_mothername"
            required
            maxlength="20"
            value="{{ student.mothername }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Guardian: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="guardianname"
            id="id_guardianname"
            required
            maxlength="20"
            value="{{ student.guardianname }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Com Address: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="comaddress"
            id="id_comaddress"
            required
            maxlength="20"
            value="{{ student.comaddress }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Perm address: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="permaddress"
            id="id_permaddress"
            required
            maxlength="20"
            value="{{ student.permaddress }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">State: </label>
        <div class="col-sm-4">
          <input
            type="text"
            name="state"
            id="id_state"
            required
            maxlength="20"
            value="{{ student.state }}"
          />
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-success">Update</button>
        </div>
      </div>
    </div>
  </form>
</html>

admissionapp/templates/admissionapp/filter.html
<html>
  <head>
    <title>Student Filter</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <h1>Student Filter</h1>
    <form method="POST" class="post-form" id="display">
      {% csrf_token %}
      <input type="Checkbox" name="blue" value="blue" checked />Blue
      <input type="Checkbox" name="red" value="red" />Red
      <input type="Checkbox" name="green" value="green" />Green
      <small id="displayerr"></small>
    </form>
    <button class="btn btn-primary" onclick="displayPage()">Display</button>
    <script>
      function displayPage() {
        var x = document.getElementById("display");
        var text = x.elements[1].value;
        var box = "";
        var val = "";
        for (var i = 0, length = x.length; i < length; i++) {
          if (x[i].checked) {
            val = x[i].value;
            box = box + val;
          }
        }
        document.getElementById("displayerr").innerHTML = box;
      }
    </script>
  </body>
</html>

admissionapp/templates/admissionapp/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">  
    <title>Student Records</title>  
     {% load static %}  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm" style="text-align: center;">  
    <thead class="thead-dark">  
    <tr>  
        <th>NAME</th>  
        <th>ID</th> 
        <th>FUNCTION</th> 
    </tr>  
    </thead>  
    <tbody>  
{% for student in students %}  
    <tr>  
        <td>{{ student.sname }}</td>  
        <td>{{ student.sid }}</td>    
        <td>  
            <a href="/edit/{{ student.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ student.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/studform" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>